chore: container check
Signed-off-by: Valery Piashchynski <piashchynski.valery@gmail.com>

diff --git a/.github/workflows/linux_durability.yml b/.github/workflows/linux_durability.yml
--- a/.github/workflows/linux_durability.yml
+++ b/.github/workflows/linux_durability.yml
@@ -67,6 +67,13 @@ jobs:
           docker-compose -f env/docker-compose-nats.yaml up -d
           sleep 30
           
+          if [ "$(docker ps -q -f status=running -f name=nats_container)" ]; then
+          echo "NATS Docker container started successfully."
+             else
+                 echo "Failed to start NATS Docker container."
+                 exit 1
+          fi
+          
           go test -timeout 20m -v -race -cover -tags=debug -failfast -coverpkg=$(cat pkgs.txt) -coverprofile=./coverage-ci/nats_dur.out -covermode=atomic jobs_nats_durability_test.go
           docker compose -f env/docker-compose-nats.yaml down
 
